const products=[{id:"100",name:"100 Diamonds",desc:"Starter pack",originalPrice:80,price:59},{id:"310",name:"310 Diamonds",desc:"Popular pack",originalPrice:240,price:220,popular:true},{id:"520",name:"520 Diamonds",desc:"Value pack",originalPrice:390,price:370},{id:"1060",name:"1060 Diamonds",desc:"Mega pack",originalPrice:760,price:740},{id:"2180",name:"2180 Diamonds",desc:"Ultra pack",originalPrice:1490,price:1470},{id:"membership",name:"Weekly Membership",desc:"Membership",originalPrice:170,price:150},{id:"monthly",name:"Monthly Membership",desc:"Membership",originalPrice:520,price:500},{id:"custom",name:"Custom Amount",desc:"Choose at checkout",price:0}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let verifiedUid="",selected=null;
function renderProducts(){$("#products").innerHTML=products.map(p=>`<article class="product magnetic-card reveal"><span class="product-glow"></span>${p.popular?'<span class="badge">POPULAR</span>':''}<div class="gem">◆</div><h3>${p.name}</h3><p>${p.desc}</p><div class="price">${p.price?`<span class="old-price">₹${p.originalPrice}</span><span class="discount-price">₹${p.price}</span>`:"Custom"}</div><button class="buy magnetic-btn" data-id="${p.id}">${p.price?"Buy now":"Choose amount"}</button></article>`).join("");wireMagnetic();revealInit();}renderProducts();
$("#themeBtn").addEventListener("click",()=>{document.body.classList.toggle("light");$("#themeBtn").textContent=document.body.classList.contains("light")?"☀":"☾"});
$("#verifyBtn").addEventListener("click",()=>{const uid=$("#uid").value.trim();if(!/^\d{6,20}$/.test(uid)){toast("Enter a valid numeric UID (6–20 digits).");$("#uid").focus();return}const btn=$("#verifyBtn");btn.disabled=true;btn.innerHTML='<span class="scan-dot"></span> Checking...';$("#verified").classList.remove("show");$("#verifyError").classList.remove("show");setTimeout(()=>{verifiedUid=uid;$("#verifiedUid").textContent=uid;$("#uidNote").textContent=`UID: ${uid} • Ready to order`;$("#verified").classList.add("show");btn.disabled=false;btn.innerHTML='Continue <span>→</span>';toast("UID accepted ✓");document.querySelector("#store").scrollIntoView({behavior:"smooth",block:"start"})},700)});
$("#uid").addEventListener("keydown",e=>{if(e.key==="Enter")$("#verifyBtn").click()});
$("#products").addEventListener("click",e=>{const btn=e.target.closest(".buy");if(!btn)return;if(!verifiedUid){toast("Enter your UID first.");document.querySelector("#topup").scrollIntoView({behavior:"smooth"});return}selected=products.find(p=>p.id===btn.dataset.id);if(selected.id==="custom"){const amount=prompt("Enter the custom INR amount:");const value=Number(amount);if(!Number.isFinite(value)||value<=0||value>100000){toast("Please enter a valid amount.");return}selected={...selected,name:"Custom Top-Up",price:Math.round(value)}}$("#orderProduct").textContent=selected.name;$("#orderPrice").textContent="₹"+selected.price;$("#orderUid").textContent=verifiedUid;$("#refId").value="";openModal()});
function openModal(){$("#modalBackdrop").classList.add("show");document.body.style.overflow="hidden"}function closeModal(){$("#modalBackdrop").classList.remove("show");document.body.style.overflow=""}$("#closeModal").addEventListener("click",closeModal);$("#modalBackdrop").addEventListener("click",e=>{if(e.target===$("#modalBackdrop"))closeModal()});
$("#confirmBtn").addEventListener("click",()=>{const ref=$("#refId").value.trim();if(!ref){toast("Enter your transaction/reference ID.");return}const order="NT-"+Date.now().toString().slice(-8);closeModal();toast(`Reference submitted • ${order}`);setTimeout(()=>alert(`Order created\n\nOrder: ${order}\nUID: ${verifiedUid}\nProduct: ${selected?.name||"—"}\nReference: ${ref}\n\nPayment is NOT automatically verified by this static site.`),250)});
$$('.faq-item').forEach(item=>item.addEventListener('click',()=>item.classList.toggle('open')));
let toastTimer;function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2600)}
function wireMagnetic(){const strength=0.28;$$('.magnetic-btn,.magnetic-card,.magnetic').forEach(el=>{if(el.dataset.magneticBound)return;el.dataset.magneticBound='1';el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;el.style.setProperty('--mx',`${x*strength}px`);el.style.setProperty('--my',`${y*strength}px`);el.classList.add('mag-active')});el.addEventListener('mouseleave',()=>{el.style.setProperty('--mx','0px');el.style.setProperty('--my','0px');el.classList.remove('mag-active')})})}
function splitMagneticHeadings(){document.querySelectorAll('[data-magnetic]').forEach(el=>{if(el.dataset.split)return;el.dataset.split='1';const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>{const frag=document.createDocumentFragment();[...node.textContent].forEach(ch=>{if(ch===' '){frag.appendChild(document.createTextNode(' '));return}const s=document.createElement('span');s.className='mag-letter';s.textContent=ch;frag.appendChild(s)});node.parentNode.replaceChild(frag,node)});el.addEventListener('mousemove',e=>{el.querySelectorAll('.mag-letter').forEach(letter=>{const r=letter.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),d=Math.hypot(dx,dy);if(d<90){const power=(1-d/90),x=(dx/d||0)*-12*power,y=(dy/d||0)*-12*power;letter.style.transform=`translate(${x}px,${y}px) scale(${1+power*.08})`;letter.style.textShadow=`0 0 ${12+power*22}px rgba(255,179,44,${.25+power*.45})`}else{letter.style.transform='';letter.style.textShadow=''}})});el.addEventListener('mouseleave',()=>el.querySelectorAll('.mag-letter').forEach(l=>{l.style.transform='';l.style.textShadow=''}))})}
function revealInit(){const items=$$('.reveal,.reveal-group .magnetic-card,.product');if(!('IntersectionObserver'in window)){items.forEach(x=>x.classList.add('visible'));return}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});items.forEach(x=>io.observe(x))}
wireMagnetic();splitMagneticHeadings();revealInit();
const glow=$(".cursor-glow");window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});$$('.tilt-card').forEach(card=>card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect(),rx=(e.clientY-r.top-r.height/2)/(r.height/2)*-5,ry=(e.clientX-r.left-r.width/2)/(r.width/2)*7;card.style.transform=`perspective(900px) rotateX(${rx}deg) rotateY(${ry}deg) translateY(-6px)`}));$$('.tilt-card').forEach(card=>card.addEventListener('mouseleave',()=>card.style.transform=''));
